- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import Vpc Variable
      include_vars: vars/vpc_setup

    - name: Create Vprofile VPC
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpcCidr}}"
        region: "{{region}}"
        dns_support: yes
        dns_hostnames: yes
        tenancy: default
        state: "{{state}}"
      register: vpcout


    - debug:
        var: vpcout

    - name: create public subntet 1 in zon1 
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{ zone }}"
        az: "{{zone1}}"
        state: "{{state}}"
        cidr: "{{PubSub1Cidr}}"
        map_public: yes
        resource_tags:
          Name: vprofile-pubsub1
      register: pubsub1_out


    - name: create public subntet 2in zone2
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{ zone }}"
        az: "{{zone2}}"
        state: "{{state}}"
        cidr: "{{PubSub2Cidr}}"
        map_public: yes
        resource_tags:
          Name: orange-pubsub2
      register: pubsub2_out

    - name: create public subntet 3 in zone3
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{ zone }}"
        az: "{{zone3}}"
        state: "{{state}}"
        cidr: "{{PubSub3Cidr}}"
        map_public: yes
        resource_tags:
          Name: orange-pubsub3
      register: pubsub3_out

    - name: create private subntet 3 in zone3
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{ zone }}"
        az: "{{zone3}}"
        state: "{{state}}"
        cidr: "{{PriSub1Cidr}}"
        resource_tags:
          Name: orange-pubsub3
      register: privsub3_out

    - name: create private subntet 3 in zone3
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{ zone }}"
        az: "{{zone3}}"
        state: "{{state}}"
        cidr: "{{PriSub2Cidr}}"
        resource_tags:
          Name: orange-privsub3
      register: privsub3_out

    - name: create private subntet 3 in zone3
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{ zone }}"
        az: "{{zone3}}"
        state: "{{state}}"
        cidr: "{{PriSub3Cidr}}"
        resource_tags:
          Name: orange-privsub3
      register: privsub3_out